@echo off
REM filepath: run.bat
REM Windows batch script to build and run RTSP project

echo ============================================
echo    RTSP Video Streaming - Windows Build
echo ============================================

REM Support a clean option to remove a stale build directory
if "%1"=="clean" (
    echo Removing existing 'build' directory (clean)...
    rmdir /S /Q build >nul 2>&1
)

REM Prevent accidental reuse of a build directory generated by a different generator
if exist build\CMakeCache.txt (
    echo Existing build directory detected. To avoid generator/toolchain mismatches,
    echo please delete the 'build' directory and re-run this script, or run this script
    echo with the argument: %~n0 clean
    pause
    exit /b 1
)

REM Create build directory
if not exist build mkdir build
cd build

REM Run CMake - detect MSVC (cl.exe) and choose an appropriate generator
echo.
echo [1/3] Configuring with CMake...

where cl.exe >nul 2>&1
if %ERRORLEVEL%==0 (
    rem Visual Studio's MSVC detected
    set "CMAKE_GENERATOR=Visual Studio 17 2022"
    set "CMAKE_ARCH=-A x64"
    echo Detected MSVC (cl.exe). Using generator: %CMAKE_GENERATOR% %CMAKE_ARCH%
)
else (
    rem Fall back to MinGW if MSVC not found
    set "CMAKE_GENERATOR=MinGW Makefiles"
    set "CMAKE_ARCH="
    echo MSVC not detected. Falling back to generator: %CMAKE_GENERATOR%
)

cmake .. -G "%CMAKE_GENERATOR%" %CMAKE_ARCH% -DCMAKE_BUILD_TYPE=Release

REM Build project
echo.
echo [2/3] Building project...
cmake --build . --config Release -j %NUMBER_OF_PROCESSORS%
if %ERRORLEVEL% neq 0 (
    echo Build failed!
    pause
    exit /b 1
)

REM Copy videos folder
echo.
echo [3/3] Copying video files...
if not exist bin\Release\videos mkdir bin\Release\videos
xcopy /Y /E ..\server\videos\* bin\Release\videos\ 2>nul

echo.
echo ============================================
echo    Build completed successfully!
echo ============================================
echo.
echo To run server:
echo    cd build\bin\Release
echo    server.exe 8554
echo.
echo To run client:
echo    cd build\bin\Release
echo    client.exe 127.0.0.1 8554 movie.Mjpeg 25000
echo.

cd ..
pause